service: social-network-api
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 2048
  stage: dev
  timeout: 15
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http: ANY /{proxy+}
      - http: ANY /
    environment:
      PORT: 4000
      DBNAME: chatdb
      USER: Administrador
      PASSWORD: url2022!
      HOST: url-db.mysql.database.azure.com
      DIALECT: mysql
      DBPORT: 3306